name: Build && Teste (CI)

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_USER: ciuser
          POSTGRES_PASSWORD: cipassword
          POSTGRES_DB: citestdb
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: citestdb
      DATABASE_USERNAME: ciuser
      DATABASE_PASSWORD: cipassword

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Node.js (18.x)
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Instalar Dependências
      run: npm ci

    - name: Rodar a Build
      run: npm run build --if-present

    - name: Rodar os Testes
      run: npm test
